// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ddm.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SwitchInputRequest_InputType int32

const (
	SwitchInputRequest_USB_C SwitchInputRequest_InputType = 0
	SwitchInputRequest_DP1   SwitchInputRequest_InputType = 1
)

var SwitchInputRequest_InputType_name = map[int32]string{
	0: "USB_C",
	1: "DP1",
}

var SwitchInputRequest_InputType_value = map[string]int32{
	"USB_C": 0,
	"DP1":   1,
}

func (x SwitchInputRequest_InputType) String() string {
	return proto.EnumName(SwitchInputRequest_InputType_name, int32(x))
}

func (SwitchInputRequest_InputType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_31420753dbebef67, []int{0, 0}
}

type SwitchInputRequest struct {
	Input                SwitchInputRequest_InputType `protobuf:"varint,1,opt,name=input,proto3,enum=ddm.SwitchInputRequest_InputType" json:"input,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *SwitchInputRequest) Reset()         { *m = SwitchInputRequest{} }
func (m *SwitchInputRequest) String() string { return proto.CompactTextString(m) }
func (*SwitchInputRequest) ProtoMessage()    {}
func (*SwitchInputRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_31420753dbebef67, []int{0}
}

func (m *SwitchInputRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SwitchInputRequest.Unmarshal(m, b)
}
func (m *SwitchInputRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SwitchInputRequest.Marshal(b, m, deterministic)
}
func (m *SwitchInputRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SwitchInputRequest.Merge(m, src)
}
func (m *SwitchInputRequest) XXX_Size() int {
	return xxx_messageInfo_SwitchInputRequest.Size(m)
}
func (m *SwitchInputRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SwitchInputRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SwitchInputRequest proto.InternalMessageInfo

func (m *SwitchInputRequest) GetInput() SwitchInputRequest_InputType {
	if m != nil {
		return m.Input
	}
	return SwitchInputRequest_USB_C
}

type SwitchInputResponse struct {
	Okay                 bool     `protobuf:"varint,1,opt,name=okay,proto3" json:"okay,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SwitchInputResponse) Reset()         { *m = SwitchInputResponse{} }
func (m *SwitchInputResponse) String() string { return proto.CompactTextString(m) }
func (*SwitchInputResponse) ProtoMessage()    {}
func (*SwitchInputResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_31420753dbebef67, []int{1}
}

func (m *SwitchInputResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SwitchInputResponse.Unmarshal(m, b)
}
func (m *SwitchInputResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SwitchInputResponse.Marshal(b, m, deterministic)
}
func (m *SwitchInputResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SwitchInputResponse.Merge(m, src)
}
func (m *SwitchInputResponse) XXX_Size() int {
	return xxx_messageInfo_SwitchInputResponse.Size(m)
}
func (m *SwitchInputResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SwitchInputResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SwitchInputResponse proto.InternalMessageInfo

func (m *SwitchInputResponse) GetOkay() bool {
	if m != nil {
		return m.Okay
	}
	return false
}

func (m *SwitchInputResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func init() {
	proto.RegisterEnum("ddm.SwitchInputRequest_InputType", SwitchInputRequest_InputType_name, SwitchInputRequest_InputType_value)
	proto.RegisterType((*SwitchInputRequest)(nil), "ddm.SwitchInputRequest")
	proto.RegisterType((*SwitchInputResponse)(nil), "ddm.SwitchInputResponse")
}

func init() { proto.RegisterFile("ddm.proto", fileDescriptor_31420753dbebef67) }

var fileDescriptor_31420753dbebef67 = []byte{
	// 207 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4c, 0x49, 0xc9, 0xd5,
	0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x4e, 0x49, 0xc9, 0x55, 0xca, 0xe3, 0x12, 0x0a, 0x2e,
	0xcf, 0x2c, 0x49, 0xce, 0xf0, 0xcc, 0x2b, 0x28, 0x2d, 0x09, 0x4a, 0x2d, 0x2c, 0x4d, 0x2d, 0x2e,
	0x11, 0x32, 0xe7, 0x62, 0xcd, 0x04, 0xf1, 0x25, 0x18, 0x15, 0x18, 0x35, 0xf8, 0x8c, 0x14, 0xf5,
	0x40, 0xba, 0x30, 0xd5, 0xe9, 0x81, 0x39, 0x21, 0x95, 0x05, 0xa9, 0x41, 0x10, 0xf5, 0x4a, 0xf2,
	0x5c, 0x9c, 0x70, 0x31, 0x21, 0x4e, 0x2e, 0xd6, 0xd0, 0x60, 0xa7, 0x78, 0x67, 0x01, 0x06, 0x21,
	0x76, 0x2e, 0x66, 0x97, 0x00, 0x43, 0x01, 0x46, 0x25, 0x7b, 0x2e, 0x61, 0x14, 0x73, 0x8a, 0x0b,
	0xf2, 0xf3, 0x8a, 0x53, 0x85, 0x84, 0xb8, 0x58, 0xf2, 0xb3, 0x13, 0x2b, 0xc1, 0xf6, 0x71, 0x04,
	0x81, 0xd9, 0x42, 0x22, 0x5c, 0xac, 0xa9, 0x45, 0x45, 0xf9, 0x45, 0x12, 0x4c, 0x0a, 0x8c, 0x1a,
	0x9c, 0x41, 0x10, 0x8e, 0x51, 0x10, 0x17, 0x9f, 0x4b, 0x66, 0x71, 0x41, 0x4e, 0x62, 0xa5, 0x6f,
	0x62, 0x5e, 0x62, 0x7a, 0x6a, 0x91, 0x90, 0x03, 0x17, 0x37, 0x92, 0x91, 0x42, 0xe2, 0x38, 0x1c,
	0x2b, 0x25, 0x81, 0x29, 0x01, 0xb1, 0xdd, 0x89, 0x3d, 0x8a, 0x15, 0x1c, 0x24, 0x49, 0x6c, 0x60,
	0xca, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0xe7, 0xc8, 0xef, 0x92, 0x26, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// DisplayManagerClient is the client API for DisplayManager service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DisplayManagerClient interface {
	SwitchInput(ctx context.Context, in *SwitchInputRequest, opts ...grpc.CallOption) (*SwitchInputResponse, error)
}

type displayManagerClient struct {
	cc *grpc.ClientConn
}

func NewDisplayManagerClient(cc *grpc.ClientConn) DisplayManagerClient {
	return &displayManagerClient{cc}
}

func (c *displayManagerClient) SwitchInput(ctx context.Context, in *SwitchInputRequest, opts ...grpc.CallOption) (*SwitchInputResponse, error) {
	out := new(SwitchInputResponse)
	err := c.cc.Invoke(ctx, "/ddm.DisplayManager/SwitchInput", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DisplayManagerServer is the server API for DisplayManager service.
type DisplayManagerServer interface {
	SwitchInput(context.Context, *SwitchInputRequest) (*SwitchInputResponse, error)
}

// UnimplementedDisplayManagerServer can be embedded to have forward compatible implementations.
type UnimplementedDisplayManagerServer struct {
}

func (*UnimplementedDisplayManagerServer) SwitchInput(ctx context.Context, req *SwitchInputRequest) (*SwitchInputResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SwitchInput not implemented")
}

func RegisterDisplayManagerServer(s *grpc.Server, srv DisplayManagerServer) {
	s.RegisterService(&_DisplayManager_serviceDesc, srv)
}

func _DisplayManager_SwitchInput_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SwitchInputRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DisplayManagerServer).SwitchInput(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ddm.DisplayManager/SwitchInput",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DisplayManagerServer).SwitchInput(ctx, req.(*SwitchInputRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _DisplayManager_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ddm.DisplayManager",
	HandlerType: (*DisplayManagerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SwitchInput",
			Handler:    _DisplayManager_SwitchInput_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ddm.proto",
}
